[package]
name = "rust2"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1.42", features = ["full"] }
dotenv = "0.15"
serde = {version="1.0.216", features = ["derive"]}
serde_json = "1.0"
serde_urlencoded = "0.7"